[env:cardputer-adv-launcher-ota]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
board_build.filesystem = littlefs
board_build.partitions = ../../contracts/launcher/cardputer-adv-8mb.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DESP32S3
    -DCARDPUTER_ADV
    -DM5GFX_BOARD=board_M5CardputerADV
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
build_src_filter = +<*> +<buddies/>
lib_deps =
    m5stack/M5Unified @ ^0.2.0
    m5stack/M5Cardputer @ ^1.1.1
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    links2004/WebSockets @ ^2.6.1
