#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/src/bridge_config.local.h"
BRIDGE_CONFIG="${CARDPUTER_BRIDGE_CONFIG:-$HOME/.claude-cardputer-bridge/config.json}"

ensure_bridge_config() {
  if [[ -f "$BRIDGE_CONFIG" ]]; then
    return
  fi
  (
    cd "$ROOT/desktop-bridge"
    npm run build >/dev/null
    node dist/index.js --print-config >/dev/null
  )
}

c_escape() {
  node -e 'process.stdout.write(String(process.argv[1] || "").replace(/\\/g, "\\\\").replace(/"/g, "\\\""))' "$1"
}

default_host() {
  if [[ -n "${CARDPUTER_BRIDGE_HOST:-}" ]]; then
    printf '%s\n' "$CARDPUTER_BRIDGE_HOST"
    return
  fi
  for dev in en0 en1; do
    ip="$(ipconfig getifaddr "$dev" 2>/dev/null || true)"
    if [[ -n "$ip" ]]; then
      printf '%s\n' "$ip"
      return
    fi
  done
  printf '127.0.0.1\n'
}

default_ssid() {
  if [[ -n "${CARDPUTER_WIFI_SSID:-}" ]]; then
    printf '%s\n' "$CARDPUTER_WIFI_SSID"
    return
  fi

  local dev raw ssid
  while IFS= read -r dev; do
    [[ -n "$dev" ]] || continue
    raw="$(networksetup -getairportnetwork "$dev" 2>/dev/null || true)"
    case "$raw" in
      "Current Wi-Fi Network: "*)
        ssid="${raw#Current Wi-Fi Network: }"
        if [[ -n "$ssid" && "$ssid" != "You are not associated with an AirPort network." ]]; then
          printf '%s\n' "$ssid"
          return
        fi
        ;;
    esac
  done < <(
    {
      networksetup -listallhardwareports 2>/dev/null |
        awk '/Hardware Port: Wi-Fi/{getline; if ($1 == "Device:") print $2}'
      printf '%s\n' en0 en1
    } | awk 'NF && !seen[$0]++'
  )
}

ensure_bridge_config

TOKEN="${CARDPUTER_BRIDGE_TOKEN:-$(node -e 'const fs=require("fs"); const p=process.env.CARDPUTER_BRIDGE_CONFIG || `${process.env.HOME}/.claude-cardputer-bridge/config.json`; process.stdout.write(JSON.parse(fs.readFileSync(p, "utf8")).token || "");')}"
PORT="${CARDPUTER_BRIDGE_PORT:-17877}"
HOST="$(default_host)"
SSID="$(default_ssid)"
PASS="${CARDPUTER_WIFI_PASS:-}"

if [[ -z "$TOKEN" ]]; then
  echo "No bridge token found. Start or print the bridge config first." >&2
  exit 1
fi

if [[ -z "$SSID" ]]; then
  echo "Could not auto-detect Wi-Fi SSID. Hotspot/tethering can hide it from macOS." >&2
  echo "Set CARDPUTER_WIFI_SSID or enter the hotspot/router SSID below." >&2
  read -r -p "Wi-Fi SSID: " SSID
fi

if [[ -z "$PASS" ]]; then
  read -r -s -p "Wi-Fi password for $SSID: " PASS
  printf '\n' >&2
fi

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
#pragma once

// Generated by scripts/write_bridge_config_header.sh.
// This file contains local secrets and is intentionally ignored by git.

#define CARDPUTER_BRIDGE_WIFI_SSID "$(c_escape "$SSID")"
#define CARDPUTER_BRIDGE_WIFI_PASS "$(c_escape "$PASS")"
#define CARDPUTER_BRIDGE_HOST "$(c_escape "$HOST")"
#define CARDPUTER_BRIDGE_PORT $PORT
#define CARDPUTER_BRIDGE_TOKEN "$(c_escape "$TOKEN")"
#define CARDPUTER_BRIDGE_FW_LABEL "cardputer-adv-bridge-dev"
EOF

chmod 600 "$OUT"
echo "Wrote $OUT"
echo "Bridge host: $HOST:$PORT"
echo "Wi-Fi SSID: $SSID"
echo "Token: configured (hidden)"
